// Yeni site metinleri (s2*) → i18n.js'in 4 dil bloğuna. Sıra: [tr, en, es, de]. Tekrar çalıştırılabilir.
import fs from 'node:fs';
const DOSYA = 'C:\\Users\\anil\\yt-extension-suite\\i18n.js';
const V = '<em class="vurgu">', VK = '</em>';
const M = {
  // --- Ortak: üst çubuk, alt bilgi ---
  s2NavUrunler: ['Eklentiler', 'Extensions', 'Extensiones', 'Erweiterungen'],
  s2NavMagaza: ['Mağaza', 'Store', 'Tienda', 'Shop'],
  s2NavLisans: ['Lisansım', 'My license', 'Mi licencia', 'Meine Lizenz'],
  s2Sepet: ['Sepet', 'Cart', 'Carrito', 'Warenkorb'],
  s2FootDesc: ['Az şey yapan ama onu iyi yapan tarayıcı eklentileri. Verin cihazında kalır, lisansı bir kez alırsın.', 'Browser extensions that do a few things, and do them well. Your data stays on your device; you pay once.', 'Extensiones de navegador que hacen pocas cosas, y las hacen bien. Tus datos se quedan en tu dispositivo; pagas una vez.', 'Browser-Erweiterungen, die wenig tun – das aber gut. Deine Daten bleiben auf deinem Gerät; du zahlst einmal.'],
  s2FootYasal: ['Yasal', 'Legal', 'Legal', 'Rechtliches'],
  s2FootIletisim: ['İletişim', 'Contact', 'Contacto', 'Kontakt'],
  s2FootHaklar: ['© 2026 Anıl Aksu. Tüm hakları saklıdır.', '© 2026 Anıl Aksu. All rights reserved.', '© 2026 Anıl Aksu. Todos los derechos reservados.', '© 2026 Anıl Aksu. Alle Rechte vorbehalten.'],
  s2FootOdeme: ['Ödemeler Polar üzerinden alınır.', 'Payments are processed by Polar.', 'Los pagos se procesan a través de Polar.', 'Zahlungen werden über Polar abgewickelt.'],
  s2Incele: ['Ayrıntılar', 'Details', 'Detalles', 'Details'],
  s2SatinAl: ['Satın al', 'Buy now', 'Comprar', 'Kaufen'],
  s2SepeteEkle: ['Sepete ekle', 'Add to cart', 'Añadir al carrito', 'In den Warenkorb'],
  s2OmurBoyu: ['Tek ödeme · ömür boyu lisans', 'One payment · lifetime license', 'Un pago · licencia de por vida', 'Einmalzahlung · lebenslange Lizenz'],
  s2Ucretsiz: ['Ücretsiz', 'Free', 'Gratis', 'Kostenlos'],
  s2Pro: ['Pro', 'Pro', 'Pro', 'Pro'],
  s2Sinirsiz: ['Sınırsız', 'Unlimited', 'Ilimitado', 'Unbegrenzt'],
  s2UcVideo: ['3 video', '3 videos', '3 vídeos', '3 Videos'],

  // --- Ana sayfa ---
  s2HubEtiket: ['Bağımsız tarayıcı eklentileri', 'Independent browser extensions', 'Extensiones de navegador independientes', 'Unabhängige Browser-Erweiterungen'],
  s2HubBaslik: [`Tarayıcında sakin, ${V}işe yarayan${VK} araçlar.`, `Calm browser tools that ${V}actually help${VK}.`, `Herramientas tranquilas que ${V}de verdad ayudan${VK}.`, `Ruhige Browser-Werkzeuge, die ${V}wirklich helfen${VK}.`],
  s2HubGiris: ['İki eklenti, tek ilke: dikkatini dağıtmadan işini yapar, verini cihazından çıkarmaz. Ücretsiz başlarsın; işine yararsa bir kez ödersin, ömür boyu senindir.', 'Two extensions, one principle: do the job without stealing your attention, and never move your data off your device. Start free; if it earns its place, pay once and keep it for life.', 'Dos extensiones, un principio: hacer su trabajo sin robarte la atención y sin sacar tus datos de tu dispositivo. Empieza gratis; si te sirve, paga una vez y es tuya para siempre.', 'Zwei Erweiterungen, ein Prinzip: ihre Arbeit tun, ohne dich abzulenken, und deine Daten nie vom Gerät holen. Starte kostenlos; wenn sie dir hilft, zahlst du einmal und behältst sie für immer.'],
  s2HubCta1: ['Eklentileri gör', 'See the extensions', 'Ver las extensiones', 'Erweiterungen ansehen'],
  s2HubCta2: ['Mağaza', 'Store', 'Tienda', 'Shop'],
  s2HubNot1: ['Abonelik yok', 'No subscription', 'Sin suscripción', 'Kein Abo'],
  s2HubNot2: ['Hesap gerekmez', 'No account needed', 'Sin cuenta', 'Kein Konto nötig'],
  s2HubNot3: ['Ücretsiz sürüm süresiz', 'Free version never expires', 'La versión gratuita no caduca', 'Gratisversion ohne Ablauf'],
  s2UrunlerEtiket: ['Eklentiler', 'Extensions', 'Extensiones', 'Erweiterungen'],
  s2UrunlerBaslik: ['Her biri tek bir işi iyi yapar.', 'Each one does one job well.', 'Cada una hace bien una sola cosa.', 'Jede macht eine Sache gut.'],
  s2UrunlerAlt: ['Ücretsiz kur ve dene. Pro\'ya yalnız ihtiyaç duyduğunda geç.', 'Install free and try it. Go Pro only when you need it.', 'Instálala gratis y pruébala. Pásate a Pro solo cuando lo necesites.', 'Kostenlos installieren und testen. Pro nur, wenn du es brauchst.'],

  s2ZenTag: ['YouTube için sinema görünümü ve video defteri', 'Cinema view and video notebook for YouTube', 'Vista de cine y cuaderno de vídeo para YouTube', 'Kinoansicht und Video-Notizbuch für YouTube'],
  s2ZenOzet: ['YouTube\'u sayfanın içinde sakin bir sinemaya çevirir. İzlerken tek tuşla not, kare ve altyazı satırı yakalarsın; hepsi videonun saniyesine bağlı bir deftere gider.', 'Turns YouTube into a calm in-page cinema. While you watch, one key captures a note, a frame or the caption line, each tied to the exact second in a notebook.', 'Convierte YouTube en un cine tranquilo dentro de la página. Mientras ves, una tecla guarda una nota, un fotograma o la línea de subtítulo, cada uno ligado a su segundo exacto en un cuaderno.', 'Macht YouTube zu einem ruhigen Kino direkt auf der Seite. Beim Schauen speichert eine Taste Notiz, Standbild oder Untertitelzeile – jeweils an die genaue Sekunde im Notizbuch gebunden.'],
  s2ZenL1: ['Sinema görünümü: oynatıcı sahneye yayılır, çevre susar', 'Cinema view: the player fills the stage, everything else goes quiet', 'Vista de cine: el reproductor ocupa el escenario y todo lo demás se calla', 'Kinoansicht: der Player füllt die Bühne, alles andere wird still'],
  s2ZenL2: ['Saniyeye bağlı not, kare görüntüsü ve altyazı satırı', 'Notes, frames and caption lines tied to the second', 'Notas, fotogramas y subtítulos ligados al segundo', 'Notizen, Standbilder und Untertitel, sekundengenau'],
  s2ZenL3: ['O anı anan yorumlar perdenin yanında belirir', 'Comments that mention this moment appear beside the screen', 'Los comentarios que mencionan ese momento aparecen junto a la pantalla', 'Kommentare zu genau diesem Moment erscheinen neben dem Bild'],
  s2ZenL4: ['Ücretsiz: 3 video defteri · Pro: sınırsız defter ve dışa aktarma', 'Free: 3 video notebooks · Pro: unlimited notebooks and export', 'Gratis: 3 cuadernos · Pro: cuadernos ilimitados y exportación', 'Gratis: 3 Notizbücher · Pro: unbegrenzt und Export'],
  s2CcTag: ['Tam sayfa ekran görüntüsü, PDF ve editör', 'Full-page screenshots, PDF and editor', 'Capturas de página completa, PDF y editor', 'Ganzseitige Screenshots, PDF und Editor'],
  s2CcOzet: ['Görünen alanın çok ötesine uzanan sayfaları tek parça yakalar. İstersen çok sayfalı PDF\'e çevirir, yerleşik editörde işaretler, hassas yerleri bulanıklaştırırsın.', 'Captures pages that run far beyond the visible area in one clean image. Turn them into multi-page PDFs, mark them up in the built-in editor, and blur anything sensitive.', 'Captura en una sola imagen páginas que van mucho más allá de lo visible. Conviértelas en PDF de varias páginas, anótalas en el editor integrado y difumina lo sensible.', 'Erfasst Seiten, die weit über den sichtbaren Bereich hinausgehen, in einem Bild. Als mehrseitiges PDF exportieren, im eingebauten Editor markieren und Sensibles verwischen.'],
  s2CcL1: ['Tam sayfa, görünür alan ya da seçtiğin bölge', 'Full page, visible area or a region you draw', 'Página completa, área visible o la región que elijas', 'Ganze Seite, sichtbarer Bereich oder eigener Ausschnitt'],
  s2CcL2: ['PNG ve JPEG dışa aktarma, ücretsiz ve süresiz', 'PNG and JPEG export, free forever', 'Exportación PNG y JPEG, gratis para siempre', 'PNG- und JPEG-Export, dauerhaft kostenlos'],
  s2CcL3: ['Stüdyo editörü: kırp, ok, kalem, bulanıklaştır, pikselleştir', 'Studio editor: crop, arrow, pen, blur, pixelate', 'Editor Studio: recorta, flechas, lápiz, difumina, pixela', 'Studio-Editor: zuschneiden, Pfeil, Stift, Weichzeichnen, Verpixeln'],
  s2CcL4: ['Pro: çok sayfalı A4 PDF ve öğe seçici', 'Pro: multi-page A4 PDF and element picker', 'Pro: PDF A4 de varias páginas y selector de elementos', 'Pro: mehrseitiges A4-PDF und Elementauswahl'],
  s2PaketBaslik: ['İkisi birlikte, tek anahtar', 'Both together, one key', 'Las dos juntas, una clave', 'Beide zusammen, ein Schlüssel'],
  s2PaketAlt: ['Zen Cinema Pro + Clean Capture Pro. Tek lisans anahtarı iki eklentide de çalışır; ayrı ayrı almaktan %22 daha uygun.', 'Zen Cinema Pro + Clean Capture Pro. One license key works in both; 22% less than buying them separately.', 'Zen Cinema Pro + Clean Capture Pro. Una sola clave funciona en ambas; un 22 % menos que por separado.', 'Zen Cinema Pro + Clean Capture Pro. Ein Lizenzschlüssel für beide; 22 % günstiger als einzeln.'],
  s2PaketCta: ['Paketi al', 'Get the bundle', 'Comprar el paquete', 'Paket kaufen'],
  s2IlkeEtiket: ['İlkeler', 'Principles', 'Principios', 'Prinzipien'],
  s2IlkeBaslik: ['Nasıl yapıyoruz', 'How we build', 'Cómo trabajamos', 'Wie wir bauen'],
  s2Ilke1B: ['Veri cihazında kalır', 'Your data stays on your device', 'Tus datos se quedan en tu dispositivo', 'Deine Daten bleiben auf dem Gerät'],
  s2Ilke1M: ['Notların, karelerin, yakaladığın sayfalar tarayıcının kendi belleğinde işlenir ve saklanır. Bizim bir sunucumuza hiçbir şey gönderilmez.', 'Your notes, frames and captured pages are processed and stored inside your browser. Nothing is sent to a server of ours.', 'Tus notas, fotogramas y capturas se procesan y guardan dentro de tu navegador. Nada se envía a un servidor nuestro.', 'Notizen, Standbilder und Aufnahmen werden in deinem Browser verarbeitet und gespeichert. Nichts geht an einen Server von uns.'],
  s2Ilke2B: ['Yalnız gereken izin', 'Only the permissions needed', 'Solo los permisos necesarios', 'Nur nötige Berechtigungen'],
  s2Ilke2M: ['Zen Cinema yalnız depolama izni ister. Her iznin neden gerektiği ürün sayfasında açıkça yazar.', 'Zen Cinema asks only for storage. Each product page explains exactly why every permission is needed.', 'Zen Cinema solo pide almacenamiento. Cada página de producto explica por qué se necesita cada permiso.', 'Zen Cinema fragt nur nach Speicher. Jede Produktseite erklärt, wofür jede Berechtigung gebraucht wird.'],
  s2Ilke3B: ['Bir kez öde', 'Pay once', 'Paga una vez', 'Einmal zahlen'],
  s2Ilke3M: ['Abonelik yok. Lisans yalnız anahtarınla Polar\'da doğrulanır; kimlik ya da kullanım bilgisi gönderilmez.', 'No subscription. The license is checked with Polar using only your key; no identity or usage data is sent.', 'Sin suscripción. La licencia se valida en Polar solo con tu clave; no se envían datos de identidad ni de uso.', 'Kein Abo. Die Lizenz wird nur mit deinem Schlüssel bei Polar geprüft; keine Identitäts- oder Nutzungsdaten.'],
  s2LisansBaslik: ['Lisans anahtarını doğrula', 'Check your license key', 'Comprueba tu clave de licencia', 'Lizenzschlüssel prüfen'],
  s2LisansAlt: ['Anahtarın Polar müşteri portalında durur; satın alırken kullandığın e-postayla girersin. Elindeki anahtarın geçerli olup olmadığını buradan sorgulayabilirsin.', 'Your key lives in the Polar customer portal; sign in with the email you used at checkout. You can check whether a key is valid here.', 'Tu clave está en el portal de clientes de Polar; entra con el correo que usaste al pagar. Aquí puedes comprobar si una clave es válida.', 'Dein Schlüssel liegt im Polar-Kundenportal; melde dich mit der E-Mail vom Kauf an. Hier kannst du prüfen, ob ein Schlüssel gültig ist.'],
  s2LisansPortal: ['Polar portalını aç', 'Open the Polar portal', 'Abrir el portal de Polar', 'Polar-Portal öffnen'],

  // --- Mağaza ---
  s2MagEtiket: ['Mağaza', 'Store', 'Tienda', 'Shop'],
  s2MagBaslik: [`Bir kez öde, ${V}hep senin${VK} olsun.`, `Pay once, ${V}keep it for good${VK}.`, `Paga una vez, ${V}es tuya para siempre${VK}.`, `Einmal zahlen, ${V}für immer behalten${VK}.`],
  s2MagAlt: ['Ödeme Polar\'ın güvenli sayfasında alınır. Üyelik gerekmez; ödemeden sonra lisans anahtarın Polar müşteri portalında hazır olur.', 'Checkout happens on Polar\'s secure page. No account needed; after payment your license key is waiting in the Polar customer portal.', 'El pago se hace en la página segura de Polar. Sin cuenta; tras pagar, tu clave te espera en el portal de clientes de Polar.', 'Bezahlt wird auf der sicheren Seite von Polar. Kein Konto nötig; danach liegt dein Schlüssel im Polar-Kundenportal.'],
  s2ZenK1: ['Sinema görünümü (Alt+C)', 'Cinema view (Alt+C)', 'Vista de cine (Alt+C)', 'Kinoansicht (Alt+C)'],
  s2ZenK2: ['Saniyeye bağlı not (Alt+N)', 'Time-stamped notes (Alt+N)', 'Notas con marca de tiempo (Alt+N)', 'Notizen mit Zeitstempel (Alt+N)'],
  s2ZenK3: ['Kare (Alt+S) ve altyazı satırı (Alt+T)', 'Frame (Alt+S) and caption line (Alt+T)', 'Fotograma (Alt+S) y subtítulo (Alt+T)', 'Standbild (Alt+S) und Untertitel (Alt+T)'],
  s2ZenK4: ['O anı anan yorumlar', 'Comments about the moment', 'Comentarios sobre el momento', 'Kommentare zum Moment'],
  s2ZenK5: ['Pro: sınırsız defter, Markdown/ZIP ve PDF dışa aktarma', 'Pro: unlimited notebooks, Markdown/ZIP and PDF export', 'Pro: cuadernos ilimitados, exportación Markdown/ZIP y PDF', 'Pro: unbegrenzte Notizbücher, Markdown/ZIP- und PDF-Export'],
  s2CcK1: ['Tam sayfa, görünür alan, bölge', 'Full page, visible area, region', 'Página completa, área visible, región', 'Ganze Seite, sichtbarer Bereich, Ausschnitt'],
  s2CcK2: ['PNG / JPEG dışa aktarma', 'PNG / JPEG export', 'Exportación PNG / JPEG', 'PNG-/JPEG-Export'],
  s2CcK3: ['Stüdyo editörü ve bulanıklaştırma', 'Studio editor and blur', 'Editor Studio y difuminado', 'Studio-Editor und Weichzeichner'],
  s2CcK4: ['Pro: çok sayfalı A4 PDF', 'Pro: multi-page A4 PDF', 'Pro: PDF A4 de varias páginas', 'Pro: mehrseitiges A4-PDF'],
  s2CcK5: ['Pro: öğe seçici (tablo, grafik, kart)', 'Pro: element picker (table, chart, card)', 'Pro: selector de elementos (tabla, gráfico, tarjeta)', 'Pro: Elementauswahl (Tabelle, Diagramm, Karte)'],
  s2PaketTag: ['İki eklenti, tek anahtar', 'Two extensions, one key', 'Dos extensiones, una clave', 'Zwei Erweiterungen, ein Schlüssel'],
  s2PaketK1: ['Zen Cinema Pro lisansı', 'Zen Cinema Pro license', 'Licencia Zen Cinema Pro', 'Zen Cinema Pro Lizenz'],
  s2PaketK2: ['Clean Capture Pro lisansı', 'Clean Capture Pro license', 'Licencia Clean Capture Pro', 'Clean Capture Pro Lizenz'],
  s2PaketK3: ['İkisinde de çalışan tek anahtar', 'One key that works in both', 'Una clave que funciona en ambas', 'Ein Schlüssel für beide'],
  s2PaketK4: ['Ayrı almaktan %22 daha uygun', '22% less than buying separately', 'Un 22 % menos que por separado', '22 % günstiger als einzeln'],
  s2PaketFiyatNot: ['İki ömür boyu lisans, tek ödeme', 'Two lifetime licenses, one payment', 'Dos licencias de por vida, un pago', 'Zwei lebenslange Lizenzen, eine Zahlung'],
  s2EnIyi: ['En avantajlı', 'Best value', 'Mejor precio', 'Bestes Angebot'],
  s2KarsEtiket: ['Karşılaştır', 'Compare', 'Comparar', 'Vergleich'],
  s2KarsBaslik: ['Ücretsiz ne verir, Pro ne ekler', 'What\'s free, what Pro adds', 'Qué es gratis y qué añade Pro', 'Was gratis ist, was Pro hinzufügt'],
  s2KarsOzellik: ['Özellik', 'Feature', 'Función', 'Funktion'],
  s2KZ1: ['Sinema görünümü ve o anı anan yorumlar', 'Cinema view and moment comments', 'Vista de cine y comentarios del momento', 'Kinoansicht und Moment-Kommentare'],
  s2KZ2: ['Video defteri (not, kare, altyazı)', 'Video notebook (note, frame, caption)', 'Cuaderno de vídeo (nota, fotograma, subtítulo)', 'Video-Notizbuch (Notiz, Standbild, Untertitel)'],
  s2KZ3: ['Markdown + görseller (ZIP) ve PDF dışa aktarma', 'Markdown + images (ZIP) and PDF export', 'Exportación Markdown + imágenes (ZIP) y PDF', 'Export als Markdown + Bilder (ZIP) und PDF'],
  s2KC1: ['Tam sayfa, görünür alan ve bölge yakalama', 'Full-page, visible-area and region capture', 'Captura completa, visible y de región', 'Ganzseiten-, Sichtbereich- und Ausschnitt-Aufnahme'],
  s2KC2: ['PNG / JPEG dışa aktarma', 'PNG / JPEG export', 'Exportación PNG / JPEG', 'PNG-/JPEG-Export'],
  s2KC3: ['Stüdyo editörü (işaretleme, bulanıklaştırma)', 'Studio editor (markup, blur)', 'Editor Studio (anotaciones, difuminado)', 'Studio-Editor (Markieren, Weichzeichnen)'],
  s2KC4: ['Çok sayfalı A4 PDF', 'Multi-page A4 PDF', 'PDF A4 de varias páginas', 'Mehrseitiges A4-PDF'],
  s2KC5: ['Öğe seçici (tablo, grafik, kart)', 'Element picker (table, chart, card)', 'Selector de elementos (tabla, gráfico, tarjeta)', 'Elementauswahl (Tabelle, Diagramm, Karte)'],
  s2DestekEtiket: ['Destek', 'Support', 'Apoyo', 'Unterstützung'],
  s2DestekBaslik: ['Beğendiysen destek olabilirsin', 'Like the work? You can chip in', '¿Te gusta? Puedes apoyar', 'Gefällt dir das? Unterstütze uns'],
  s2SssEtiket: ['Sorular', 'Questions', 'Preguntas', 'Fragen'],
  s2SssBaslik: ['Sık sorulanlar', 'Frequently asked', 'Preguntas frecuentes', 'Häufige Fragen'],
  s2S1: ['Lisans anahtarımı nereden alırım?', 'Where do I get my license key?', '¿Dónde consigo mi clave?', 'Wo bekomme ich meinen Schlüssel?'],
  s2C1: ['Ödemeden sonra Polar müşteri portalına, satın alırken kullandığın e-postayla girersin; anahtarın orada durur. Kopyalayıp eklentinin lisans alanına yapıştırırsın.', 'After payment, sign in to the Polar customer portal with the email you used at checkout; your key is there. Copy it into the extension\'s license field.', 'Tras el pago, entra en el portal de clientes de Polar con el correo que usaste; tu clave está allí. Cópiala en el campo de licencia de la extensión.', 'Nach der Zahlung meldest du dich mit der Kauf-E-Mail im Polar-Kundenportal an; dort liegt dein Schlüssel. Kopiere ihn ins Lizenzfeld der Erweiterung.'],
  s2S4: ['Nasıl ödeme yaparım?', 'How do I pay?', '¿Cómo pago?', 'Wie bezahle ich?'],
  s2C4: ['Ödeme Polar\'ın güvenli ödeme sayfasında kartla alınır. Kart bilgin bu siteye hiç gelmez.', 'Payment is taken by card on Polar\'s secure checkout page. Your card details never touch this site.', 'El pago se hace con tarjeta en la página segura de Polar. Los datos de tu tarjeta nunca pasan por este sitio.', 'Bezahlt wird per Karte auf der sicheren Polar-Seite. Deine Kartendaten berühren diese Website nie.'],
  s2S6: ['Ücretsiz sürüm ne kadar çalışır?', 'How long does the free version work?', '¿Cuánto dura la versión gratuita?', 'Wie lange läuft die Gratisversion?'],
  s2C6: ['Süresiz. Zen Cinema\'da sinema görünümü, yorumlar ve 3 video defteri; Clean Capture\'da yakalama, PNG/JPEG ve editör hep ücretsiz kalır.', 'Forever. Zen Cinema keeps cinema view, comments and 3 notebooks free; Clean Capture keeps capture, PNG/JPEG and the editor free.', 'Para siempre. En Zen Cinema la vista de cine, los comentarios y 3 cuadernos; en Clean Capture la captura, PNG/JPEG y el editor siguen gratis.', 'Unbegrenzt. Bei Zen Cinema bleiben Kinoansicht, Kommentare und 3 Notizbücher gratis; bei Clean Capture Aufnahme, PNG/JPEG und Editor.'],
  s2GuvenB: ['Ödeme Polar üzerinden', 'Checkout by Polar', 'Pago a través de Polar', 'Bezahlung über Polar'],
  s2GuvenM: ['Kart bilgin bu siteye gelmez; ödeme Polar\'ın güvenli sayfasında alınır.', 'Your card details never reach this site; payment happens on Polar\'s secure page.', 'Los datos de tu tarjeta no llegan a este sitio; el pago se hace en la página segura de Polar.', 'Deine Kartendaten erreichen diese Seite nie; bezahlt wird auf der sicheren Polar-Seite.'],
  s2OdemeyeGec: ['Ödemeye geç', 'Continue to payment', 'Continuar al pago', 'Weiter zur Zahlung'],

  // --- Zen Cinema ürün sayfası ---
  s2zEtiket: ['Zen Cinema · YouTube için', 'Zen Cinema · for YouTube', 'Zen Cinema · para YouTube', 'Zen Cinema · für YouTube'],
  s2zBaslik: [`Videodan ${V}kopmadan${VK} öğren.`, `Learn without ${V}leaving${VK} the video.`, `Aprende sin ${V}salir${VK} del vídeo.`, `Lernen, ohne das Video zu ${V}verlassen${VK}.`],
  s2zGiris: ['Zen Cinema, YouTube\'un üstüne sakin bir katman ekler: sinema görünümü, saniyeye bağlı notlar, kareler ve o anı anan yorumlar. Hepsi birkaç tuş uzağında.', 'Zen Cinema adds a calm layer on top of YouTube: cinema view, notes tied to the second, frames and comments about the moment. All a few keys away.', 'Zen Cinema añade una capa tranquila sobre YouTube: vista de cine, notas ligadas al segundo, fotogramas y comentarios del momento. Todo a unas teclas.', 'Zen Cinema legt eine ruhige Ebene über YouTube: Kinoansicht, sekundengenaue Notizen, Standbilder und Kommentare zum Moment. Alles nur ein paar Tasten entfernt.'],
  s2zIndir: ['Ücretsiz indir', 'Download free', 'Descargar gratis', 'Kostenlos laden'],
  s2zNot3: ['Veriler cihazında', 'Data stays on device', 'Datos en tu dispositivo', 'Daten bleiben lokal'],
  s2zHareketEtiket: ['Altı hareket', 'Six moves', 'Seis gestos', 'Sechs Handgriffe'],
  s2zHareketBaslik: ['Altı hareket, tek defter', 'Six moves, one notebook', 'Seis gestos, un cuaderno', 'Sechs Handgriffe, ein Notizbuch'],
  s2zHareketAlt: ['Her şey klavyeden ya da oynatıcının sağ altındaki çubuktan. İlk kurulumda iki dakikalık uygulamalı tur hepsini gerçek bir videoda gösterir.', 'Everything works from the keyboard or the bar at the player\'s bottom right. On first install, a two-minute guided tour shows each one on a real video.', 'Todo funciona con el teclado o con la barra abajo a la derecha del reproductor. Al instalar, un recorrido de dos minutos te los enseña en un vídeo real.', 'Alles per Tastatur oder über die Leiste unten rechts am Player. Nach der Installation zeigt eine zweiminütige Tour alles an einem echten Video.'],
  s2zH1B: ['Sinema görünümü', 'Cinema view', 'Vista de cine', 'Kinoansicht'],
  s2zH1M: ['Oynatıcı sahneye yayılır, sayfanın geri kalanı söner. Fare durunca arayüz de susar.', 'The player fills the stage and the rest of the page fades. Stop the mouse and the controls go quiet too.', 'El reproductor ocupa el escenario y el resto se apaga. Si no mueves el ratón, la interfaz también se calla.', 'Der Player füllt die Bühne, der Rest der Seite tritt zurück. Ruht die Maus, verschwinden auch die Bedienelemente.'],
  s2zH2B: ['Saniyeye bağlı not', 'Note tied to the second', 'Nota ligada al segundo', 'Sekundengenaue Notiz'],
  s2zH2M: ['Video durur, not alanı açılır. Enter ile kaydet, izlemeye devam et. Ekrandaki altyazı da nota eklenir.', 'The video pauses and a note field opens. Press Enter to save and keep watching. The on-screen caption is added too.', 'El vídeo se pausa y se abre un campo de nota. Pulsa Enter para guardar y sigue viendo. El subtítulo en pantalla también se añade.', 'Das Video pausiert, ein Notizfeld öffnet sich. Mit Enter speichern und weiterschauen. Der Untertitel auf dem Bild wird mitgespeichert.'],
  s2zH3B: ['Kare görüntüsü', 'Frame capture', 'Captura de fotograma', 'Standbild'],
  s2zH3M: ['O anın görüntüsü deftere düşer. Tahtadaki formül, slayttaki şema kaybolmaz.', 'The current frame lands in your notebook. The formula on the board or the diagram on the slide stays with you.', 'El fotograma actual va a tu cuaderno. La fórmula de la pizarra o el esquema de la diapositiva no se pierden.', 'Das aktuelle Bild landet im Notizbuch. Formel an der Tafel oder Diagramm auf der Folie bleiben erhalten.'],
  s2zH4B: ['Altyazı satırı', 'Caption line', 'Línea de subtítulo', 'Untertitelzeile'],
  s2zH4M: ['Ekrandaki altyazıyı tek tuşla alıntılar. Altyazı kapalıysa kendisi açar.', 'Quotes the on-screen caption with one key. Turns captions on if they\'re off.', 'Cita el subtítulo en pantalla con una tecla. Si están desactivados, los activa.', 'Zitiert den sichtbaren Untertitel mit einer Taste. Schaltet Untertitel bei Bedarf ein.'],
  s2zH5B: ['Defter', 'Notebook', 'Cuaderno', 'Notizbuch'],
  s2zH5M: ['Notlar, kareler ve alıntılar zamana göre dizilir. Bir zamana tıkla, video o saniyeye gider.', 'Notes, frames and quotes line up by time. Click a timestamp and the video jumps there.', 'Notas, fotogramas y citas se ordenan por tiempo. Pulsa una marca y el vídeo salta a ese segundo.', 'Notizen, Standbilder und Zitate nach Zeit sortiert. Klick auf eine Zeit, und das Video springt dorthin.'],
  s2zH6B: ['Anlar', 'Moments', 'Momentos', 'Momente'],
  s2zH6M: ['Yorumlarda geçen zaman damgalarını toplar. Başkalarının neyi önemli bulduğunu görürsün.', 'Collects the timestamps people mention in comments, so you see what others found worth pointing at.', 'Reúne las marcas de tiempo que aparecen en los comentarios: ves qué les pareció importante a otros.', 'Sammelt Zeitstempel aus den Kommentaren – so siehst du, was andere wichtig fanden.'],
  s2zDugme: ['Düğme', 'Button', 'Botón', 'Taste'],
  s2zSekme: ['Sekme', 'Tab', 'Pestaña', 'Tab'],
  s2zGaleriEtiket: ['Ekranlar', 'Screens', 'Pantallas', 'Ansichten'],
  s2zGaleriBaslik: ['Gerçek arayüz, gerçek videoda', 'The real interface, on a real video', 'La interfaz real, en un vídeo real', 'Die echte Oberfläche, an einem echten Video'],
  s2zG1: ['Sinema görünümü ve yan panel', 'Cinema view with the side panel', 'Vista de cine con el panel lateral', 'Kinoansicht mit Seitenleiste'],
  s2zG2: ['Saniyeye bağlı not', 'A note tied to the second', 'Una nota ligada al segundo', 'Eine sekundengenaue Notiz'],
  s2zG3: ['Defter paneli', 'Notebook panel', 'Panel del cuaderno', 'Notizbuch-Leiste'],
  s2zG4: ['Anlar: yorumlardaki zamanlar', 'Moments: timestamps from comments', 'Momentos: marcas en los comentarios', 'Momente: Zeitstempel aus Kommentaren'],
  s2zG5: ['Tüm defterler sayfası', 'All notebooks page', 'Página de todos los cuadernos', 'Seite mit allen Notizbüchern'],
  s2zPlanEtiket: ['Sürümler', 'Plans', 'Planes', 'Versionen'],
  s2zPlanBaslik: ['Ücretsiz başla, gerekince Pro', 'Start free, go Pro when you need it', 'Empieza gratis, pásate a Pro cuando quieras', 'Kostenlos starten, Pro bei Bedarf'],
  s2zU1: ['Tüm hareketler: sinema, not, kare, altyazı, anlar', 'Every move: cinema, note, frame, caption, moments', 'Todos los gestos: cine, nota, fotograma, subtítulo, momentos', 'Alle Handgriffe: Kino, Notiz, Standbild, Untertitel, Momente'],
  s2zU2: ['3 videoya kadar defter', 'Notebooks for up to 3 videos', 'Cuadernos para hasta 3 vídeos', 'Notizbücher für bis zu 3 Videos'],
  s2zU3: ['Süresiz, hesap gerekmez', 'No time limit, no account', 'Sin límite de tiempo ni cuenta', 'Ohne Zeitlimit, ohne Konto'],
  s2zP1: ['Sınırsız video defteri', 'Unlimited video notebooks', 'Cuadernos de vídeo ilimitados', 'Unbegrenzte Video-Notizbücher'],
  s2zP2: ['Markdown + görseller (ZIP) dışa aktarma', 'Markdown + images (ZIP) export', 'Exportación Markdown + imágenes (ZIP)', 'Export als Markdown + Bilder (ZIP)'],
  s2zP3: ['Yazdırılabilir PDF', 'Printable PDF', 'PDF imprimible', 'Druckbares PDF'],
  s2zP4: ['Ömür boyu güncellemeler', 'Lifetime updates', 'Actualizaciones de por vida', 'Lebenslange Updates'],
  s2zSpecEtiket: ['Gizlilik', 'Privacy', 'Privacidad', 'Datenschutz'],
  s2zSpecBaslik: ['Neye dokunur, neye dokunmaz', 'What it touches, and what it doesn\'t', 'Qué toca y qué no', 'Was sie berührt – und was nicht'],
  s2zS1: ['İzinler', 'Permissions', 'Permisos', 'Berechtigungen'],
  s2zS1V: ['Yalnız depolama (storage). Geçmiş, sekmeler ya da diğer siteler okunmaz.', 'Storage only. No history, tabs or other sites are read.', 'Solo almacenamiento. No lee el historial, las pestañas ni otros sitios.', 'Nur Speicher. Kein Zugriff auf Verlauf, Tabs oder andere Seiten.'],
  s2zS2: ['Çalıştığı yer', 'Runs on', 'Funciona en', 'Läuft auf'],
  s2zS2V: ['Yalnız youtube.com izleme sayfaları', 'youtube.com watch pages only', 'Solo páginas de vídeo de youtube.com', 'Nur youtube.com-Videoseiten'],
  s2zS3: ['Verilerin', 'Your data', 'Tus datos', 'Deine Daten'],
  s2zS3V: ['Tarayıcının kendi deposunda (IndexedDB). Sunucuya gitmez.', 'In your browser\'s own storage (IndexedDB). Never sent to a server.', 'En el almacenamiento del navegador (IndexedDB). Nunca va a un servidor.', 'Im Browser-eigenen Speicher (IndexedDB). Geht an keinen Server.'],
  s2zS4: ['Ağ', 'Network', 'Red', 'Netzwerk'],
  s2zS4V: ['Yalnız Pro anahtarı girildiğinde Polar\'a doğrulama isteği', 'Only a license check to Polar when you enter a Pro key', 'Solo una validación con Polar al introducir una clave Pro', 'Nur eine Lizenzprüfung bei Polar, wenn du einen Pro-Schlüssel eingibst'],
  s2zS5: ['Reklamlar', 'Ads', 'Anuncios', 'Werbung'],
  s2zS5V: ['Dokunmaz. Reklam sırasında kayıt almaz, reklam bitince devam eder.', 'Left alone. Nothing is saved during an ad; it continues when the ad ends.', 'No los toca. No guarda nada durante un anuncio; sigue al terminar.', 'Bleibt unangetastet. Während Werbung wird nichts gespeichert; danach geht es weiter.'],
  s2zS6: ['Diller', 'Languages', 'Idiomas', 'Sprachen'],
  s2zS6V: ['Türkçe, İngilizce, İspanyolca, Almanca', 'Turkish, English, Spanish, German', 'Turco, inglés, español, alemán', 'Türkisch, Englisch, Spanisch, Deutsch'],
  s2zS7: ['Sürüm', 'Version', 'Versión', 'Version'],
  s2zKurEtiket: ['Kurulum', 'Install', 'Instalación', 'Installation'],
  s2zKurAlt: ['Chrome Web Store incelemesi sürerken eklentiyi doğrudan buradan kurabilirsin. Mağaza onayından sonra güncellemeler otomatik gelir.', 'While the Chrome Web Store review is in progress, you can install it straight from here. Once approved, updates arrive automatically.', 'Mientras la revisión de Chrome Web Store sigue en curso, puedes instalarla desde aquí. Tras la aprobación, las actualizaciones llegan solas.', 'Solange die Prüfung im Chrome Web Store läuft, kannst du sie direkt hier installieren. Nach der Freigabe kommen Updates automatisch.'],
  s2zSonBaslik: ['Bir sonraki dersi farklı izle.', 'Watch your next lesson differently.', 'Mira tu próxima clase de otra forma.', 'Schau deine nächste Lektion anders.'],
  s2zSonAlt: ['Ücretsiz kur, iki dakikalık turu yap. İşine yararsa Pro bir kez alınır, ömür boyu senindir.', 'Install free and take the two-minute tour. If it helps, Pro is a one-time purchase that\'s yours for life.', 'Instálala gratis y haz el recorrido de dos minutos. Si te sirve, Pro es un único pago para siempre.', 'Kostenlos installieren, Zwei-Minuten-Tour machen. Wenn es hilft: Pro ist ein Einmalkauf für immer.'],

  // --- Clean Capture ürün sayfası ---
  s2cEtiket: ['Clean Capture · ekran ve PDF', 'Clean Capture · screen & PDF', 'Clean Capture · pantalla y PDF', 'Clean Capture · Bildschirm & PDF'],
  s2cBaslik: [`Sayfanın ${V}tamamı${VK}, tek görüntüde.`, `The ${V}whole${VK} page, in one image.`, `La página ${V}entera${VK}, en una imagen.`, `Die ${V}ganze${VK} Seite, in einem Bild.`],
  s2cGiris: ['Görünen alanın ötesine taşan sayfaları kaydırmadan, yapışkan başlıkları tekrarlamadan tek parça yakalar. PNG, JPEG ya da çok sayfalı PDF olarak kaydedersin; yakalama tamamen tarayıcında olur.', 'Captures pages that run past the visible area as a single image, without scrolling or repeating sticky headers. Save as PNG, JPEG or multi-page PDF; capture happens entirely in your browser.', 'Captura en una sola imagen páginas que van más allá de lo visible, sin desplazar ni repetir cabeceras fijas. Guarda en PNG, JPEG o PDF de varias páginas; todo ocurre en tu navegador.', 'Erfasst Seiten jenseits des sichtbaren Bereichs als ein Bild – ohne Scrollen, ohne doppelte Sticky-Header. Als PNG, JPEG oder mehrseitiges PDF speichern; alles passiert in deinem Browser.'],
  s2cKur: ['Chrome\'a ücretsiz ekle', 'Add to Chrome, free', 'Añadir a Chrome gratis', 'Kostenlos zu Chrome hinzufügen'],
  s2cNot1: ['Chrome Web Store\'da', 'On the Chrome Web Store', 'En Chrome Web Store', 'Im Chrome Web Store'],
  s2cOzEtiket: ['Neler yapar', 'What it does', 'Qué hace', 'Was sie kann'],
  s2cOzBaslik: ['Yakala, düzenle, paylaş', 'Capture, edit, share', 'Captura, edita, comparte', 'Erfassen, bearbeiten, teilen'],
  s2cOzAlt: ['Dört yakalama biçimi, üç dışa aktarma biçimi ve yerleşik bir editör.', 'Four ways to capture, three export formats and a built-in editor.', 'Cuatro formas de capturar, tres formatos de exportación y un editor integrado.', 'Vier Aufnahmearten, drei Exportformate und ein eingebauter Editor.'],
  s2cO1B: ['Tam sayfa', 'Full page', 'Página completa', 'Ganze Seite'],
  s2cO1M: ['Kaydırılabilir tüm içerik tek görüntüde. Sayfa kaydırılmaz, başlıklar tekrarlanmaz.', 'All scrollable content in one image. The page isn\'t scrolled and headers aren\'t repeated.', 'Todo el contenido desplazable en una imagen. Sin desplazar la página ni repetir cabeceras.', 'Der gesamte scrollbare Inhalt in einem Bild. Ohne Scrollen, ohne doppelte Kopfzeilen.'],
  s2cO2B: ['Görünür alan', 'Visible area', 'Área visible', 'Sichtbarer Bereich'],
  s2cO2M: ['Ekranda o an ne varsa, anında.', 'Whatever is on screen right now, instantly.', 'Lo que hay en pantalla ahora mismo, al instante.', 'Was gerade auf dem Bildschirm ist, sofort.'],
  s2cO3B: ['Özel bölge', 'Custom region', 'Región personalizada', 'Eigener Ausschnitt'],
  s2cO3M: ['Ekranda bir kutu çiz, yalnız o kısmı al.', 'Draw a box on screen and capture just that part.', 'Dibuja un recuadro y captura solo esa parte.', 'Rahmen aufziehen und nur diesen Teil erfassen.'],
  s2cO4B: ['Öğe seçici', 'Element picker', 'Selector de elementos', 'Elementauswahl'],
  s2cO4M: ['Bir tabloya, grafiğe ya da karta tıkla; yalnız o öğe piksel hassasiyetinde yakalanır.', 'Click a table, chart or card and capture exactly that element.', 'Haz clic en una tabla, gráfico o tarjeta y captura solo ese elemento.', 'Tabelle, Diagramm oder Karte anklicken – genau dieses Element wird erfasst.'],
  s2cO5B: ['Çok sayfalı PDF', 'Multi-page PDF', 'PDF de varias páginas', 'Mehrseitiges PDF'],
  s2cO5M: ['Uzun görüntü A4 sayfalara bölünür; baskıya ve paylaşıma hazır.', 'Long captures are split into A4 pages, ready to print or share.', 'Las capturas largas se dividen en páginas A4, listas para imprimir o compartir.', 'Lange Aufnahmen werden auf A4-Seiten verteilt – druck- und teilfertig.'],
  s2cO6B: ['Stüdyo editörü', 'Studio editor', 'Editor Studio', 'Studio-Editor'],
  s2cO6M: ['Kırp, ok ve dikdörtgen çiz, kalemle işaretle; hassas bilgileri bulanıklaştır ya da pikselleştir.', 'Crop, draw arrows and boxes, mark up with a pen; blur or pixelate anything sensitive.', 'Recorta, dibuja flechas y recuadros, marca con lápiz; difumina o pixela lo sensible.', 'Zuschneiden, Pfeile und Rahmen, Stift; Sensibles weichzeichnen oder verpixeln.'],
  s2cG1: ['Tek tıkla yakalama menüsü', 'One-click capture menu', 'Menú de captura con un clic', 'Aufnahme-Menü mit einem Klick'],
  s2cG2: ['Pro: öğe seçici ve PDF', 'Pro: element picker and PDF', 'Pro: selector de elementos y PDF', 'Pro: Elementauswahl und PDF'],
  s2cG3: ['Stüdyo editörü', 'Studio editor', 'Editor Studio', 'Studio-Editor'],
  s2cU1: ['Tam sayfa, görünür alan ve bölge yakalama', 'Full-page, visible-area and region capture', 'Captura completa, visible y de región', 'Ganzseiten-, Sichtbereich- und Ausschnitt-Aufnahme'],
  s2cU2: ['PNG ve JPEG dışa aktarma', 'PNG and JPEG export', 'Exportación PNG y JPEG', 'PNG- und JPEG-Export'],
  s2cU3: ['Stüdyo editörü ve bulanıklaştırma', 'Studio editor with blur', 'Editor Studio con difuminado', 'Studio-Editor mit Weichzeichner'],
  s2cP1: ['Çok sayfalı A4 PDF', 'Multi-page A4 PDF', 'PDF A4 de varias páginas', 'Mehrseitiges A4-PDF'],
  s2cP2: ['Öğe seçici', 'Element picker', 'Selector de elementos', 'Elementauswahl'],
  s2cIzinBaslik: ['Her izin, neden gerekli', 'Every permission, and why', 'Cada permiso y su porqué', 'Jede Berechtigung – und warum'],
  s2cIz1: ['Yalnız simgeye ya da kısayola bastığında, o an açık olan sekmeyi yakalamak için. Diğer sekmelere erişmez.', 'Only when you click the icon or shortcut, to capture the tab you\'re on. No access to other tabs.', 'Solo al pulsar el icono o el atajo, para capturar la pestaña actual. Sin acceso a otras.', 'Nur bei Klick auf Symbol oder Kürzel, um den aktuellen Tab zu erfassen. Kein Zugriff auf andere Tabs.'],
  s2cIz2: ['Öğe ve bölge seçme arayüzünü yalnız tıkladığın sekmeye eklemek için.', 'To show the element and region picker only in the tab you clicked.', 'Para mostrar el selector de elementos y regiones solo en la pestaña elegida.', 'Um die Element- und Ausschnittauswahl nur im gewählten Tab anzuzeigen.'],
  s2cIz3: ['Tam sayfa görüntüyü kaydırmadan tek parça almak için Chrome\'un kendi ekran görüntüsü komutu. Görüntü alınınca hemen ayrılır; ağ trafiği ya da çerez okunmaz.', 'Chrome\'s own screenshot command, to take the full page in one piece without scrolling. It detaches right after; no network traffic or cookies are read.', 'El comando de captura de Chrome, para tomar la página completa sin desplazarla. Se desconecta enseguida; no lee tráfico ni cookies.', 'Chromes eigener Screenshot-Befehl, um die ganze Seite ohne Scrollen zu erfassen. Trennt sich sofort danach; kein Netzwerkverkehr, keine Cookies.'],
  s2cIz4: ['Ürettiğin PNG, JPEG ya da PDF dosyasını bilgisayarına kaydetmek için.', 'To save the PNG, JPEG or PDF you create to your computer.', 'Para guardar en tu equipo el PNG, JPEG o PDF que creas.', 'Um das erstellte PNG, JPEG oder PDF auf deinem Rechner zu speichern.'],
  s2cIz5: ['Parçaları tek görüntüde birleştirmek için görünmez bir yerel sayfa. Ağa çıkmaz.', 'An invisible local page that stitches pieces into one image. Never goes online.', 'Una página local invisible que une las partes en una imagen. No se conecta a la red.', 'Eine unsichtbare lokale Seite, die Teile zu einem Bild zusammensetzt. Ohne Netzwerk.'],
  s2cIz6: ['Tercihlerini ve varsa Pro anahtarını yalnız bu tarayıcıda saklamak için.', 'To keep your preferences and any Pro key in this browser only.', 'Para guardar tus preferencias y tu clave Pro solo en este navegador.', 'Um Einstellungen und ggf. den Pro-Schlüssel nur in diesem Browser zu speichern.'],
  s2cSonBaslik: ['Bir dahaki uzun sayfayı tek seferde al.', 'Grab the next long page in one go.', 'Captura la próxima página larga de una vez.', 'Die nächste lange Seite in einem Rutsch.'],
  s2cSonAlt: ['Yakalama, PNG/JPEG ve editör hep ücretsiz. PDF ve öğe seçici için Pro bir kez alınır.', 'Capture, PNG/JPEG and the editor are always free. Pro adds PDF and the element picker, one payment.', 'Captura, PNG/JPEG y editor siempre gratis. Pro añade PDF y el selector, en un solo pago.', 'Aufnahme, PNG/JPEG und Editor sind immer gratis. Pro ergänzt PDF und Elementauswahl – einmalig.'],

  // --- Sepet ve ödeme penceresi ---
  s2CheckoutBaslik: ['Siparişi tamamla', 'Complete your order', 'Completa tu pedido', 'Bestellung abschließen'],
  s2Toplam: ['Toplam', 'Total', 'Total', 'Summe'],
  s2EpostaEtiket: ['E-posta adresin', 'Your email', 'Tu correo', 'Deine E-Mail'],
  s2EpostaIpucu: ['Polar müşteri portalına bu adresle girip anahtarını görürsün.', 'You\'ll use this address to open the Polar customer portal and see your key.', 'Con este correo entrarás al portal de Polar para ver tu clave.', 'Mit dieser Adresse öffnest du das Polar-Kundenportal und siehst deinen Schlüssel.'],
  s2AdEtiket: ['Ad soyad (isteğe bağlı)', 'Full name (optional)', 'Nombre (opcional)', 'Name (optional)'],
  s2LisansYer: ['Lisans anahtarın', 'Your license key', 'Tu clave de licencia', 'Dein Lizenzschlüssel'],
  s2C2: ['Hayır. Hesap ya da şifre gerekmez; yalnız e-posta adresini girersin. Polar portalına bu adresle girip anahtarını görürsün.', 'No. No account or password; just your email. You\'ll use it to open the Polar portal and see your key.', 'No. Sin cuenta ni contraseña; solo tu correo. Con él entras al portal de Polar y ves tu clave.', 'Nein. Kein Konto, kein Passwort – nur deine E-Mail. Damit öffnest du das Polar-Portal und siehst deinen Schlüssel.'],
  s2CheckoutAlt: ['Üyelik gerekmez. Ödemeden sonra anahtarın Polar müşteri portalında hazır olur; eklentinin lisans alanına yapıştırırsın.', 'No account needed. After payment your key is ready in the Polar customer portal; paste it into the extension\'s license field.', 'Sin cuenta. Tras el pago, tu clave está lista en el portal de clientes de Polar; pégala en el campo de licencia de la extensión.', 'Kein Konto nötig. Nach der Zahlung liegt dein Schlüssel im Polar-Kundenportal; füge ihn ins Lizenzfeld der Erweiterung ein.'],
  s2Kapat: ['Kapat', 'Close', 'Cerrar', 'Schließen'],

  // --- Yasal sayfalar ---
  s2GeriMagaza: ['← Mağazaya dön', '← Back to the store', '← Volver a la tienda', '← Zurück zum Shop']
};

const DILLER = ['tr', 'en', 'es', 'de'];
let s = fs.readFileSync(DOSYA, 'utf8');
const eol = s.includes('\r\n') ? '\r\n' : '\n';
s = s.replace(/^[ \t]+s2[A-Za-z0-9]+: .*,\r?\n/gm, ''); // eski s2 satırları
let eksik = 0;
DILLER.forEach((d, i) => {
  const ac = new RegExp(`^(\\s*${d}: \\{)\\r?\\n`, 'm');
  if (!ac.test(s)) throw new Error('dil bloğu yok: ' + d);
  const satirlar = Object.entries(M).map(([k, v]) => { if (!v[i]) eksik++; return `    ${k}: ${JSON.stringify(v[i] || v[1])},`; }).join(eol);
  s = s.replace(ac, (t, a) => a + eol + satirlar + eol);
});
fs.writeFileSync(DOSYA, s, 'utf8');
// Doğrulama: dosya JS olarak çalışıyor mu, her dilde anahtarlar var mı?
const vm = await import('node:vm');
const ctx = { localStorage: { getItem: () => 'tr', setItem() {} }, document: { addEventListener() {}, querySelectorAll: () => [] } };
vm.createContext(ctx);
vm.runInContext(s + '\nthis.T = TRANSLATIONS;', ctx);
const say = DILLER.map((d) => Object.keys(M).filter((k) => ctx.T[d][k] === M[k][DILLER.indexOf(d)]).length);
console.log(`anahtar: ${Object.keys(M).length} · dil başına doğru: ${say.join('/')} · eksik çeviri: ${eksik}`);
